# Generated by Django 5.0.6 on 2024-05-23 15:36

import filebrowser.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='slide title')),
                ('subtitle', models.TextField(verbose_name='slide subtitle')),
                ('image', filebrowser.fields.FileBrowseField(max_length=255, verbose_name='slide image')),
            ],
            options={
                'verbose_name': 'slide',
                'verbose_name_plural': 'slides',
            },
        ),
    ]
