# Generated by Django 5.0.6 on 2024-05-23 14:33

import filebrowser.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=filebrowser.fields.FileBrowseField(default='', max_length=255, verbose_name='company logo'),
            preserve_default=False,
        ),
    ]
