# Generated by Django 5.0.6 on 2024-05-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AC', 'Active'), ('PA', 'Passive')], default='', max_length=2, verbose_name='product category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='product title'),
            preserve_default=False,
        ),
    ]
