# Generated by Django 5.0.6 on 2024-05-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AC', 'Active'), ('WI', 'Wireless'), ('CC', 'Camera'), ('PO', 'Power & Earth'), ('TO', 'Tower')], max_length=2, verbose_name='product category'),
        ),
    ]
