# Generated by Django 5.0.6 on 2024-05-23 18:36

import filebrowser.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=filebrowser.fields.FileBrowseField(default='', max_length=255, verbose_name='product image'),
            preserve_default=False,
        ),
    ]
